<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>RetroArch</RootNamespace>
    <AssemblyName>RetroArch</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Launcher.Core/Launcher.Core.csproj" />
    <ProjectReference Include="../Launcher.Infrastructure/Launcher.Infrastructure.csproj" />
  </ItemGroup>

</Project>
