<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">net8.0</TargetFrameworks>
        <TargetFrameworks Condition="'$(TargetFrameworks)' != ''">$(TargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <RootNamespace>MelonDS.Plugin</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../Launcher.Core/Launcher.Core.csproj" />
        <ProjectReference Include="../../Launcher.Infrastructure/Launcher.Infrastructure.csproj" />
    </ItemGroup>
</Project>
