<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Launcher.Core\Launcher.Core.csproj" />
    <ProjectReference Include="..\Launcher.Infrastructure\Launcher.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Shirtfffff.png" />
    <AvaloniaResource Include="Assets\Shirtfffff.png" />
    <None Remove="Assets\logo.png" />
    <AvaloniaResource Include="Assets\logo.png" />
    <AvaloniaResource Include="Assets\placeholder.png" />
    <None Include="bin\Debug\net10.0\Plugins\Mupen64Plus\plugin.json" />
    <None Include="bin\Debug\net8.0\Plugins\Mupen64Plus\plugin.json" />
    <None Include="bin\Debug\net9.0\Plugins\Mupen64Plus\plugin.json" />
    <None Include="bin\Debug\net8.0\Plugins\Azahar\plugin.json" />
    <None Include="bin\Debug\net8.0\Plugins\MelonDS\plugin.json" />
    <None Include="bin\Debug\net8.0\Plugins\Snesx9\plugin.json" />
    <None Include="bin\Debug\net8.0\Plugins\Cemu\plugin.json" />
    <None Remove="Assets\logoicon.png" />
    <None Remove="Assets\logoicon.ico" />
    <AvaloniaResource Include="Assets\logoicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net10.0\Plugins\Installers\cemu.install.sh" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\dolphin.install.sh" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\emulators.install.ps1" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\install_azahar.sh" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\install_melonds.sh" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\install_mupen64plus.bat" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\install_mupen64plus.sh" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\install_snes9x.sh" />
    <Content Include="bin\Debug\net10.0\Plugins\Installers\retroarch.install.sh" />
    <Content Include="bin\Debug\net10.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.deps.json" />
    <Content Include="bin\Debug\net10.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.dll" />
    <Content Include="bin\Debug\net10.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Installers\install_azahar.sh" />
    <Content Include="bin\Debug\net8.0\Installers\install_cemu.sh" />
    <Content Include="bin\Debug\net8.0\Installers\dolphin.install.sh" />
    <Content Include="bin\Debug\net8.0\Installers\emulators.install.ps1" />
    <Content Include="bin\Debug\net8.0\Installers\install_melonds.sh" />
    <Content Include="bin\Debug\net8.0\Installers\install_mupen64plus.bat" />
    <Content Include="bin\Debug\net8.0\Installers\install_mupen64plus.sh" />
    <Content Include="bin\Debug\net8.0\Installers\retroarch.install.sh" />
    <Content Include="bin\Debug\net8.0\Installers\install_snes9x.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\Azahar.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\Azahar.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\Azahar.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\manifest.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Cemu\Cemu.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Cemu\Cemu.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Cemu\Cemu.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\Cemu\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\MelonDS.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\MelonDS.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\MelonDS.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\SNESx9.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\SNESx9.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\SNESx9.Plugin.pdb" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\cemu.install.sh" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\dolphin.install.sh" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\emulators.install.ps1" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\install_azahar.sh" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\install_melonds.sh" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\install_mupen64plus.bat" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\install_mupen64plus.sh" />
    <Content Include="bin\Debug\net9.0\Plugins\Installers\install_snes9x.sh" />
    <Content Include="bin\Debug\net9.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.deps.json" />
    <Content Include="bin\Debug\net9.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.dll" />
    <Content Include="bin\Debug\net9.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.pdb" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\logo.png" />
    <Resource Include="Assets\logo.png" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks Condition="'$(TargetFrameworks)' == ''">net8.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(TargetFrameworks)' != ''">$(TargetFrameworks)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
