<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Launcher.Core\Launcher.Core.csproj" />
    <ProjectReference Include="..\Launcher.Infrastructure\Launcher.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Shirtfffff.png" />
    <AvaloniaResource Include="Assets\Shirtfffff.png" />
    <None Include="bin\Debug\net8.0\Plugins\Mupen64Plus\plugin.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0\Installers\install_azahar.sh" />
    <Content Include="bin\Debug\net8.0\Installers\cemu.install.sh" />
    <Content Include="bin\Debug\net8.0\Installers\dolphin.install.sh" />
    <Content Include="bin\Debug\net8.0\Installers\emulators.install.ps1" />
    <Content Include="bin\Debug\net8.0\Installers\install_melonds.sh" />
    <Content Include="bin\Debug\net8.0\Installers\install_mupen64plus.sh" />
    <Content Include="bin\Debug\net8.0\Installers\retroarch.install.sh" />
    <Content Include="bin\Debug\net8.0\Installers\install_snes9x.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\Azahar.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\Azahar.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\Azahar.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\manifest.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Azahar\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Citra3DS\Citra3DS.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Citra3DS\Citra3DS.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Citra3DS\Citra3DS.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\Citra3DS\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\azahar.install.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\cemu.install.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\dolphin.install.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\emulators.install.ps1" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\melonDS.install.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\mupen64plus.install.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\retroarch.install.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\Installers\snes9x.install.sh" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\MelonDS.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\MelonDS.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\MelonDS.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\MelonDS\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Mupen64Plus\Mupen64Plus.Plugin.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\RetroArch\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\RetroArch\RetroArch.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\RetroArch\RetroArch.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\RetroArch\RetroArch.pdb" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\plugin.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\SNESx9.Plugin.deps.json" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\SNESx9.Plugin.dll" />
    <Content Include="bin\Debug\net8.0\Plugins\Snesx9\SNESx9.Plugin.pdb" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
